name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t mlops-breastcancer .

    - name: Test API endpoint
      run: |
        docker run -d -p 5000:5000 --name test_mlops mlops-breastcancer
        sleep 10
        curl http://127.0.0.1:5000/
        docker stop test_mlops
        docker rm test_mlops
